language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.9.7
install:
  - pip install coveralls coverage
  - pip install Django==$DJANGO_VERSION
  - python setup.py install
script: coverage run --source=simple_links manage.py test
after_success:
  - coveralls
